{'turn right':'motion',
 'turn left':'motion',
 'go straight':'motion',
 'go back':'motion',
 'follow me':'motion',
 'save location':'event',
 'stop following':'motion',
 'start go get it':'event',
 'start ggi learning':'event',
 'start test phase':'event'
 }
